[workspace]
[package]
version = "0.1.0"
name = "img-editor-program"
edition = "2021"

[dependencies]
serde = "1.0.196"
serde_json = "1.0.113"
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
lib = { path = "../lib" }
image = "0.24.8"