[workspace]
[package]
version = "0.1.0"
name = "img-editor-script"
edition = "2021"

[dependencies]
image = "0.24.8"
serde_json = "1.0.113"
sp1-core = { git = "https://github.com/succinctlabs/sp1.git" }
lib = { path = "../lib" }
